import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { createInterface } from "node:readline/promises";
import { fileURLToPath } from "node:url";
import {
  BASE_FIELD_NAMES,
  type FieldDef,
  SQL_TYPE,
  TS_TYPE,
  ask,
  askMenu,
  askYesNo,
  c,
  detectPackageManager,
  editPopulateExpr,
  formInputJsx,
  formatWithBiome,
  insertValueExpr,
  log,
  nextMigrationPrefix,
  payloadFieldExpr,
  promptFieldCore,
  runMigration,
  tableCellExpr,
  toPascal,
  updateAssignExpr,
  zodExpr,
} from "./lib/shared";

/**
 * Adds one or more fields to an EXISTING module generated by
 * .nexthono/create-module.ts (backend + migration + frontend), by patching the
 * already-generated files in place rather than regenerating them — so any
 * unrelated hand-edits survive. Run with:
 *
 *   npm run nexthono-field
 *
 * Only modules that look like they were produced by create-module.ts are
 * offered (detected via the `mapRow` helper in repository.ts) — the `users`
 * reference module has bespoke auth logic that doesn't match this shape, so
 * it's intentionally excluded.
 */

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(__dirname, "..");

const BACKEND_V1_DIR = join(projectRoot, "server", "api", "v1");
const MIGRATIONS_DIR = join(projectRoot, "server", "api", "database", "migrations");
const SRC_TYPES_DIR = join(projectRoot, "src", "types");
const SRC_SERVICES_DIR = join(projectRoot, "src", "services");
const SRC_APP_DIR = join(projectRoot, "src", "app");

interface ModuleInfo {
  table: string;
  Pascal: string;
  camelSingular: string;
  camelPlural: string;
  paths: {
    types: string;
    schema: string;
    repository: string;
    service: string;
    frontendType: string;
    frontendService: string;
    frontendPage: string;
  };
}

// ---------------------------------------------------------------------------
// Module discovery
// ---------------------------------------------------------------------------

function listEligibleModules(): string[] {
  if (!existsSync(BACKEND_V1_DIR)) return [];
  return readdirSync(BACKEND_V1_DIR, { withFileTypes: true })
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .filter((table) => {
      const repoPath = join(BACKEND_V1_DIR, table, "repository.ts");
      if (!existsSync(repoPath)) return false;
      return readFileSync(repoPath, "utf8").includes("function mapRow(");
    })
    .sort();
}

function findFrontendTypeFile(pascal: string): string | null {
  if (!existsSync(SRC_TYPES_DIR)) return null;
  for (const file of readdirSync(SRC_TYPES_DIR)) {
    if (!file.endsWith(".ts")) continue;
    const p = join(SRC_TYPES_DIR, file);
    if (readFileSync(p, "utf8").includes(`export type ${pascal} = {`)) return p;
  }
  return null;
}

function loadModuleInfo(table: string): ModuleInfo {
  const backendDir = join(BACKEND_V1_DIR, table);
  const typesPath = join(backendDir, "types.ts");
  const schemaPath = join(backendDir, "schema.ts");
  const repositoryPath = join(backendDir, "repository.ts");
  const servicePath = join(backendDir, "service.ts");

  const typesContent = readFileSync(typesPath, "utf8");
  const pascalMatch = typesContent.match(/export type (\w+)Row = BaseFields/);
  if (!pascalMatch) throw new Error(`No se pudo leer el tipo de fila en ${typesPath}`);
  const Pascal = pascalMatch[1];

  const repositoryContent = readFileSync(repositoryPath, "utf8");
  const repoMatch = repositoryContent.match(/export const (\w+)Repository = \{/);
  if (!repoMatch) throw new Error(`No se pudo leer el repositorio en ${repositoryPath}`);
  const camelSingular = repoMatch[1];

  const controllerContent = readFileSync(join(backendDir, "controller.ts"), "utf8");
  const controllerMatch = controllerContent.match(/export const (\w+)Controller = \{/);
  if (!controllerMatch) throw new Error(`No se pudo leer el controller en ${backendDir}`);
  const camelPlural = controllerMatch[1];

  const frontendTypeFile = findFrontendTypeFile(Pascal);
  if (!frontendTypeFile)
    throw new Error(`No se encontró el tipo de frontend para "${Pascal}" en src/types/.`);

  const frontendServicePath = join(SRC_SERVICES_DIR, `${table}.service.ts`);
  if (!existsSync(frontendServicePath)) {
    throw new Error(`No se encontró ${frontendServicePath}`);
  }

  const frontendPagePath = join(SRC_APP_DIR, table, "page.tsx");
  if (!existsSync(frontendPagePath)) {
    throw new Error(`No se encontró ${frontendPagePath}`);
  }

  return {
    table,
    Pascal,
    camelSingular,
    camelPlural,
    paths: {
      types: typesPath,
      schema: schemaPath,
      repository: repositoryPath,
      service: servicePath,
      frontendType: frontendTypeFile,
      frontendService: frontendServicePath,
      frontendPage: frontendPagePath,
    },
  };
}

/** Field names already declared in create${Pascal}Schema (backend). */
function existingFieldNames(schemaContent: string, Pascal: string): Set<string> {
  // A module created with zero fields collapses to `z.object({});` on one
  // line — nothing to collect.
  if (schemaContent.includes(`export const create${Pascal}Schema = z.object({});`)) {
    return new Set<string>();
  }

  const startAnchor = `export const create${Pascal}Schema = z.object({\n`;
  const startIdx = schemaContent.indexOf(startAnchor);
  if (startIdx === -1) throw new Error(`No se encontró create${Pascal}Schema en schema.ts`);
  const endIdx = schemaContent.indexOf("\n});", startIdx);
  if (endIdx === -1)
    throw new Error(`No se encontró el cierre de create${Pascal}Schema en schema.ts`);
  const block = schemaContent.slice(startIdx + startAnchor.length, endIdx);
  const names = new Set<string>();
  for (const line of block.split("\n")) {
    const m = line.match(/^\s*(\w+):/);
    if (m) names.add(m[1]);
  }
  return names;
}

// ---------------------------------------------------------------------------
// Text-splicing primitives
// ---------------------------------------------------------------------------

/** Replaces the text strictly between `startAnchor` and `endAnchor` (first occurrence at/after `from`). */
function spliceBetween(
  content: string,
  startAnchor: string,
  endAnchor: string,
  transform: (between: string) => string,
  from = 0,
): string {
  const startIdx = content.indexOf(startAnchor, from);
  if (startIdx === -1)
    throw new Error(`No se encontró el marcador de inicio: ${JSON.stringify(startAnchor)}`);
  const bodyStart = startIdx + startAnchor.length;
  const endIdx = content.indexOf(endAnchor, bodyStart);
  if (endIdx === -1)
    throw new Error(`No se encontró el marcador de fin: ${JSON.stringify(endAnchor)}`);
  const between = content.slice(bodyStart, endIdx);
  return content.slice(0, bodyStart) + transform(between) + content.slice(endIdx);
}

function insertBeforeLiteral(
  content: string,
  literal: string,
  insertion: string,
  from = 0,
): string {
  const idx = content.indexOf(literal, from);
  if (idx === -1) throw new Error(`No se encontró: ${JSON.stringify(literal)}`);
  return content.slice(0, idx) + insertion + content.slice(idx);
}

function appendLine(between: string, line: string): string {
  return between.length > 0 ? `${between}\n${line}` : line;
}

/**
 * A module created with zero domain fields has empty blocks (`{}`,
 * `z.object({})`, ...) that biome collapses onto a single line. Before
 * splicing a new field into such a block, expand it back to the multi-line
 * skeleton every other patcher expects. No-op if the block isn't collapsed.
 */
function expandIfCollapsed(content: string, collapsed: string, expanded: string): string {
  return content.includes(collapsed) ? content.replace(collapsed, expanded) : content;
}

// ---------------------------------------------------------------------------
// Per-file patchers — each takes the current file content and the NEW fields
// being added (existing fields are untouched) and returns the patched content.
// ---------------------------------------------------------------------------

function patchTypesTs(initialContent: string, Pascal: string, fields: FieldDef[]): string {
  let content = initialContent;
  content = expandIfCollapsed(
    content,
    `export type ${Pascal}Row = BaseFields & {};`,
    `export type ${Pascal}Row = BaseFields & {\n\n};`,
  );
  content = expandIfCollapsed(
    content,
    `export type Create${Pascal}Input = {};`,
    `export type Create${Pascal}Input = {\n\n};`,
  );

  for (const f of fields) {
    content = spliceBetween(content, `export type ${Pascal}Row = BaseFields & {\n`, "\n};", (b) =>
      appendLine(b, `  ${f.name}: ${TS_TYPE[f.type]}${f.required ? "" : " | null"};`),
    );
    content = spliceBetween(content, `export type Create${Pascal}Input = {\n`, "\n};", (b) =>
      appendLine(b, `  ${f.name}${f.required ? "" : "?"}: ${TS_TYPE[f.type]};`),
    );
  }
  return content;
}

function patchSchemaTs(initialContent: string, Pascal: string, fields: FieldDef[]): string {
  let content = initialContent;
  content = expandIfCollapsed(
    content,
    `export const create${Pascal}Schema = z.object({});`,
    `export const create${Pascal}Schema = z.object({\n\n});`,
  );
  content = expandIfCollapsed(
    content,
    `export const update${Pascal}Schema = z.object({});`,
    `export const update${Pascal}Schema = z\n  .object({\n\n  });`,
  );

  for (const f of fields) {
    content = spliceBetween(
      content,
      `export const create${Pascal}Schema = z.object({\n`,
      "\n});",
      (b) => appendLine(b, `  ${f.name}: ${zodExpr(f, false)},`),
    );

    const updateStart = `export const update${Pascal}Schema = z\n  .object({\n`;
    content = spliceBetween(content, updateStart, "\n  })", (b) =>
      appendLine(b, `    ${f.name}: ${zodExpr(f, true)},`),
    );
  }

  // If the module had zero fields before, the update schema never got a
  // `.refine(...)` clause (nothing to require). Add it now that it has fields.
  const updateStart = `export const update${Pascal}Schema = z\n  .object({\n`;
  const startIdx = content.indexOf(updateStart);
  if (startIdx !== -1) {
    const closeAnchor = "\n  })";
    const closeIdx = content.indexOf(closeAnchor, startIdx);
    if (closeIdx !== -1) {
      const afterClose = closeIdx + closeAnchor.length;
      if (!content.slice(afterClose, afterClose + 10).startsWith("\n  .refine")) {
        content = `${content.slice(0, afterClose)}\n  .refine((d) => Object.keys(d).length > 0, { message: "At least one field is required" })${content.slice(afterClose)}`;
      }
    }
  }

  return content;
}

function patchRepositoryTs(
  initialContent: string,
  Pascal: string,
  table: string,
  fields: FieldDef[],
): string {
  let content = initialContent;
  // 1) Raw<Pascal>Row omit union + extra props (boolean fields only). Biome
  // wraps this onto multiple lines once it's long enough (2+ boolean
  // fields), so match across newlines ([\s\S] instead of .) and normalize
  // whitespace before appending rather than assuming a single physical line.
  const booleanFieldsToAdd = fields.filter((f) => f.type === "boolean");
  if (booleanFieldsToAdd.length > 0) {
    const rawLineRe = new RegExp(
      `type Raw${Pascal}Row = Omit<${Pascal}Row, ([\\s\\S]*?)> & \\{([\\s\\S]*?)\\};`,
    );
    const rawMatch = content.match(rawLineRe);
    if (!rawMatch) throw new Error(`No se encontró "type Raw${Pascal}Row" en repository.ts`);
    let omitUnion = rawMatch[1].replace(/\s+/g, " ").trim();
    let rawExtra = rawMatch[2].replace(/\s+/g, " ").trim().replace(/;$/, "");
    for (const f of booleanFieldsToAdd) {
      omitUnion += ` | "${f.name}"`;
      rawExtra += `; ${f.name}: number`;
    }
    content = content.replace(
      rawLineRe,
      `type Raw${Pascal}Row = Omit<${Pascal}Row, ${omitUnion}> & { ${rawExtra} };`,
    );
  }

  // 2) mapRow(): Boolean(row.<field>) lines. When the module had zero boolean
  // fields, biome collapses the blank line between `...mapDeleted(row),` and
  // `};`, so the "between" capture may or may not already end in `\n` —
  // normalize before appending.
  const booleanFields = fields.filter((f) => f.type === "boolean");
  if (booleanFields.length > 0) {
    content = spliceBetween(
      content,
      `function mapRow(row: Raw${Pascal}Row): ${Pascal}Row {\n  return {\n    ...mapDeleted(row),\n`,
      "  };\n}",
      (b) => {
        const trimmed = b.replace(/\n$/, "");
        return `${booleanFields.reduce(
          (acc, f) => appendLine(acc, `    ${f.name}: Boolean(row.${f.name}),`),
          trimmed,
        )}\n`;
      },
    );
  }

  // 3) findBy<Field>() methods for unique fields — inserted right before create().
  const uniqueFields = fields.filter((f) => f.unique);
  if (uniqueFields.length > 0) {
    const createSig = `\n  async create(data: Create${Pascal}Input, actorId: string | null = null): Promise<${Pascal}Row> {\n`;
    const methods = uniqueFields
      .map(
        (f) => `
  async findBy${toPascal(f.name)}(${f.name}: ${TS_TYPE[f.type]}): Promise<${Pascal}Row | null> {
    const row = await getDb()
      .prepare("SELECT * FROM ${table} WHERE ${f.name} = ? AND deleted = 0")
      .bind(${f.name})
      .first<Raw${Pascal}Row>();
    return row ? mapRow(row) : null;
  },`,
      )
      .join("");
    // A blank line separates the last findBy() from create() in generated
    // output; insertBeforeLiteral abuts them otherwise since createSig
    // starts with only a single newline.
    content = insertBeforeLiteral(content, createSig, `${methods}\n`);
  }

  // 4) INSERT column list + VALUES placeholder list.
  const colsRe = /\(id, date_entered, date_modified, create_by, modified_by, deleted((?:, \w+)*)\)/;
  if (!colsRe.test(content))
    throw new Error("No se encontró la lista de columnas del INSERT en repository.ts");
  content = content.replace(colsRe, (_m, suffix: string) => {
    const extra = fields.map((f) => `, ${f.name}`).join("");
    return `(id, date_entered, date_modified, create_by, modified_by, deleted${suffix}${extra})`;
  });
  const valuesRe = /VALUES \(([?, ]+)\)/;
  if (!valuesRe.test(content))
    throw new Error("No se encontró la lista de VALUES del INSERT en repository.ts");
  content = content.replace(valuesRe, (_m, placeholders: string) => {
    const extra = fields.map(() => ", ?").join("");
    return `VALUES (${placeholders}${extra})`;
  });

  // 5) create(): new positional value lines inside `.bind(...)`, appended after
  // the six base binds. As with mapRow(), a module with zero existing domain
  // fields collapses this to `base.deleted,\n      )` with no field lines in
  // between, so the "between" capture may or may not already end in `\n` —
  // normalize first. Column list, VALUES `?` list and bind args all grow at the
  // end, so their order stays aligned.
  content = spliceBetween(content, "        base.deleted,\n", "      )\n      .first<", (b) => {
    const trimmed = b.replace(/\n$/, "");
    return `${fields.reduce(
      (acc, f) => appendLine(acc, `        ${insertValueExpr(f)},`),
      trimmed,
    )}\n`;
  });

  // 6) update(): new `if (data.<field> !== undefined) {...}` blocks, scoped to
  //    the update() method only (softDelete() also calls touchBaseFields).
  const updateSig = `  async update(\n    id: string,\n    data: Update${Pascal}Input,`;
  const updateSigIdx = content.indexOf(updateSig);
  if (updateSigIdx === -1) throw new Error("No se encontró el método update() en repository.ts");
  const touchAnchor = "\n\n    const touch = touchBaseFields(actorId);";
  const touchIdx = content.indexOf(touchAnchor, updateSigIdx);
  if (touchIdx === -1)
    throw new Error("No se encontró el punto de inserción dentro de update() en repository.ts");
  const ifBlocks = fields
    .map(
      (f) => `\n    if (data.${f.name} !== undefined) {
      sets.push("${f.name} = ?");
      params.push(${updateAssignExpr(f)});
    }`,
    )
    .join("");
  content = content.slice(0, touchIdx) + ifBlocks + content.slice(touchIdx);

  return content;
}

function patchServiceTs(initialContent: string, camelSingular: string, fields: FieldDef[]): string {
  const uniqueFields = fields.filter((f) => f.unique);
  if (uniqueFields.length === 0) return initialContent;

  let content = initialContent;

  const createChecks = uniqueFields
    .map(
      (
        f,
      ) => `    if (input.${f.name} !== undefined && (await ${camelSingular}Repository.findBy${toPascal(f.name)}(input.${f.name}))) {
      throw conflict("${f.label} already in use");
    }
`,
    )
    .join("");
  content = insertBeforeLiteral(
    content,
    `return ${camelSingular}Repository.create(input, actorId);`,
    createChecks,
  );

  const updateChecks = uniqueFields
    .map(
      (f) => `    if (input.${f.name} !== undefined && input.${f.name} !== existing.${f.name}) {
      const clash = await ${camelSingular}Repository.findBy${toPascal(f.name)}(input.${f.name});
      if (clash && clash.id !== id) throw conflict("${f.label} already in use");
    }
`,
    )
    .join("");
  content = insertBeforeLiteral(
    content,
    `const updated = await ${camelSingular}Repository.update(id, input, actorId);`,
    updateChecks,
  );

  return content;
}

function patchFrontendTypeTs(initialContent: string, Pascal: string, fields: FieldDef[]): string {
  let content = initialContent;
  for (const f of fields) {
    content = spliceBetween(content, `export type ${Pascal} = {\n`, "\n};", (b) =>
      appendLine(b, `  ${f.name}: ${TS_TYPE[f.type]}${f.required ? "" : " | null"};`),
    );
  }
  return content;
}

function patchFrontendServiceTs(
  initialContent: string,
  Pascal: string,
  fields: FieldDef[],
): string {
  let content = initialContent;
  content = expandIfCollapsed(
    content,
    `export type Create${Pascal}Payload = {};`,
    `export type Create${Pascal}Payload = {\n\n};`,
  );

  for (const f of fields) {
    content = spliceBetween(content, `export type Create${Pascal}Payload = {\n`, "\n};", (b) =>
      appendLine(b, `  ${f.name}${f.required ? "" : "?"}: ${TS_TYPE[f.type]};`),
    );
  }
  return content;
}

function patchFrontendPageTsx(initialContent: string, Pascal: string, fields: FieldDef[]): string {
  let content = initialContent;
  content = expandIfCollapsed(content, "type FormState = {};", "type FormState = {\n\n};");
  content = expandIfCollapsed(
    content,
    "const emptyForm: FormState = {};",
    "const emptyForm: FormState = {\n\n};",
  );
  content = expandIfCollapsed(
    content,
    "    setForm({});\n    setEditingId(item.id);",
    "    setForm({\n\n    });\n    setEditingId(item.id);",
  );
  content = expandIfCollapsed(
    content,
    `      const payload = {} as Create${Pascal}Payload;`,
    `      const payload = {\n\n      } as Create${Pascal}Payload;`,
  );

  for (const f of fields) {
    content = spliceBetween(content, "type FormState = {\n", "\n};", (b) =>
      appendLine(b, `  ${f.name}: ${f.type === "boolean" ? "boolean" : "string"};`),
    );
    content = spliceBetween(content, "const emptyForm: FormState = {\n", "\n};", (b) =>
      appendLine(b, `  ${f.name}: ${f.type === "boolean" ? "false" : '""'},`),
    );
    content = spliceBetween(content, "setForm({\n", "\n    });\n    setEditingId(item.id);", (b) =>
      appendLine(b, `      ${f.name}: ${editPopulateExpr(f)},`),
    );
    content = spliceBetween(content, "const payload = {\n", "\n      } as Create", (b) =>
      appendLine(b, `        ${f.name}: ${payloadFieldExpr(f)},`),
    );
    content = insertBeforeLiteral(
      content,
      `                <th className="px-4 py-2 font-medium">Alta</th>`,
      `                <th className="px-4 py-2 font-medium">${f.label}</th>\n`,
    );
    content = insertBeforeLiteral(
      content,
      `                  <td className="px-4 py-2 text-[var(--muted-foreground)]">\n                    {formatDate(item.date_entered)}`,
      `                  <td className="px-4 py-2">{${tableCellExpr(f)}}</td>\n`,
    );
    content = insertBeforeLiteral(
      content,
      `          {formError && <p className="text-sm text-red-500 sm:col-span-2">{formError}</p>}`,
      `${formInputJsx(f)}\n`,
    );
  }

  const colSpanMatch = content.match(/colSpan=\{(\d+)\}/);
  if (!colSpanMatch) throw new Error("No se encontró colSpan={...} en page.tsx");
  const newColSpan = Number.parseInt(colSpanMatch[1], 10) + fields.length;
  content = content.replace(/colSpan=\{\d+\}/, `colSpan={${newColSpan}}`);

  return content;
}

// ---------------------------------------------------------------------------
// Migration
// ---------------------------------------------------------------------------

function sqlDefaultLiteral(f: FieldDef): string {
  if (f.type === "boolean") return "0";
  return f.sqlDefault ?? "";
}

function genAlterMigrationSql(
  prefix: string,
  table: string,
  fields: FieldDef[],
): { filename: string; sql: string } {
  const alters = fields.map((f) => {
    let line = `ALTER TABLE ${table} ADD COLUMN ${f.name} ${SQL_TYPE[f.type]}`;
    if (f.required) line += ` NOT NULL DEFAULT ${sqlDefaultLiteral(f)}`;
    return `${line};`;
  });

  const indexBlocks = fields
    .filter((f) => f.unique)
    .map(
      (f) =>
        `\nCREATE UNIQUE INDEX IF NOT EXISTS idx_${table}_${f.name}_active\n  ON ${table} (${f.name}) WHERE deleted = 0;`,
    );

  const label = fields.length === 1 ? fields[0].name : "fields";
  return {
    filename: `${prefix}_add_${label}_to_${table}.sql`,
    sql: `-- ${prefix}_add_${label}_to_${table}: agrega ${fields.map((f) => f.name).join(", ")} a ${table}.

${alters.join("\n")}
${indexBlocks.join("\n")}
`,
  };
}

// ---------------------------------------------------------------------------
// Prompts
// ---------------------------------------------------------------------------

async function promptSqlDefault(
  rl: ReturnType<typeof createInterface>,
  f: Pick<FieldDef, "type" | "label">,
): Promise<string> {
  if (f.type === "boolean") return "0";
  for (;;) {
    const raw = await ask(
      rl,
      `Valor por defecto para las filas existentes (requerido porque "${f.label}" es obligatorio): `,
    );
    if (!raw) {
      log(
        `${c.red}Este campo es requerido: hace falta un valor por defecto para las filas ya existentes.${c.reset}`,
      );
      continue;
    }
    if (f.type === "integer") {
      if (!/^-?\d+$/.test(raw)) {
        log(`${c.red}Debe ser un número entero.${c.reset}`);
        continue;
      }
      return raw;
    }
    if (f.type === "decimal") {
      if (!/^-?\d+(\.\d+)?$/.test(raw)) {
        log(`${c.red}Debe ser un número.${c.reset}`);
        continue;
      }
      return raw;
    }
    // string / date
    return `'${raw.replace(/'/g, "''")}'`;
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function printBanner() {
  log("");
  log(
    `${c.bold}${c.cyan}◆  nexthono-field${c.reset}${c.dim} — agrega campos a un módulo existente${c.reset}`,
  );
  log("");
}

async function main() {
  printBanner();

  const modules = listEligibleModules();
  if (modules.length === 0) {
    log(
      `${c.red}✖ No hay módulos compatibles todavía. Crea uno con "nexthono-module" primero.${c.reset}`,
    );
    process.exitCode = 1;
    return;
  }

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  const choice = await askMenu(rl, "Selecciona el módulo:", modules);
  const table = modules[choice - 1];

  let info: ModuleInfo;
  try {
    info = loadModuleInfo(table);
  } catch (err) {
    log(`${c.red}✖ ${err instanceof Error ? err.message : err}${c.reset}`);
    rl.close();
    process.exitCode = 1;
    return;
  }

  const schemaContent = readFileSync(info.paths.schema, "utf8");
  const existing = existingFieldNames(schemaContent, info.Pascal);
  for (const name of BASE_FIELD_NAMES) existing.add(name);

  const fields: FieldDef[] = [];
  for (;;) {
    const addMore = await askYesNo(rl, "\n¿Desea agregar un campo adicional?");
    if (!addMore) break;

    const core = await promptFieldCore(rl, existing);

    let sqlDefault: string | undefined;
    if (core.required && core.type !== "boolean") {
      sqlDefault = await promptSqlDefault(rl, core);
      log(
        `${c.yellow}⚠ Si "${table}" ya tiene más de una fila y el campo es único, este valor repetido hará fallar el índice único al migrar.${c.reset}`,
      );
    }

    const field: FieldDef = { ...core, sqlDefault };
    existing.add(field.name);
    fields.push(field);
    log(
      `${c.green}✔ Campo "${field.name}" (${field.type}${field.required ? ", requerido" : ""}${field.unique ? ", único" : ""}) agregado.${c.reset}`,
    );
  }

  rl.close();

  if (fields.length === 0) {
    log(`${c.dim}No se agregó ningún campo.${c.reset}`);
    return;
  }

  log(`\n${c.dim}Aplicando ${fields.length} campo(s) a "${table}"…${c.reset}`);

  const originals = {
    types: readFileSync(info.paths.types, "utf8"),
    schema: readFileSync(info.paths.schema, "utf8"),
    repository: readFileSync(info.paths.repository, "utf8"),
    service: readFileSync(info.paths.service, "utf8"),
    frontendType: readFileSync(info.paths.frontendType, "utf8"),
    frontendService: readFileSync(info.paths.frontendService, "utf8"),
    frontendPage: readFileSync(info.paths.frontendPage, "utf8"),
  };

  try {
    const patched = {
      types: patchTypesTs(originals.types, info.Pascal, fields),
      schema: patchSchemaTs(originals.schema, info.Pascal, fields),
      repository: patchRepositoryTs(originals.repository, info.Pascal, table, fields),
      service: patchServiceTs(originals.service, info.camelSingular, fields),
      frontendType: patchFrontendTypeTs(originals.frontendType, info.Pascal, fields),
      frontendService: patchFrontendServiceTs(originals.frontendService, info.Pascal, fields),
      frontendPage: patchFrontendPageTsx(originals.frontendPage, info.Pascal, fields),
    };

    // Nothing is written until every patch above has succeeded.
    writeFileSync(info.paths.types, patched.types, "utf8");
    writeFileSync(info.paths.schema, patched.schema, "utf8");
    writeFileSync(info.paths.repository, patched.repository, "utf8");
    writeFileSync(info.paths.service, patched.service, "utf8");
    writeFileSync(info.paths.frontendType, patched.frontendType, "utf8");
    writeFileSync(info.paths.frontendService, patched.frontendService, "utf8");
    writeFileSync(info.paths.frontendPage, patched.frontendPage, "utf8");
  } catch (err) {
    log(
      `${c.red}✖ No se pudo parchear el módulo automáticamente: ${err instanceof Error ? err.message : err}${c.reset}`,
    );
    log(
      `${c.yellow}No se modificó ningún archivo — probablemente el módulo fue editado a mano y ya no coincide con el patrón generado. Agrega el campo manualmente.${c.reset}`,
    );
    process.exitCode = 1;
    return;
  }

  const migrationFiles = readdirSync(MIGRATIONS_DIR).filter((f) => f.endsWith(".sql"));
  const prefix = nextMigrationPrefix(migrationFiles);
  const { filename, sql } = genAlterMigrationSql(prefix, table, fields);
  const migrationPath = join(MIGRATIONS_DIR, filename);
  writeFileSync(migrationPath, sql, "utf8");

  log(`${c.green}✔ Módulo "${table}" actualizado. Migración ${filename} generada.${c.reset}`);

  formatWithBiome(projectRoot, [
    info.paths.types,
    info.paths.schema,
    info.paths.repository,
    info.paths.service,
    info.paths.frontendType,
    info.paths.frontendService,
    info.paths.frontendPage,
  ]);

  const rl2 = createInterface({ input: process.stdin, output: process.stdout });
  const runNow = await askYesNo(rl2, "\n¿Ejecutar la migración ahora (db:migrate)?");
  rl2.close();

  if (runNow) {
    const pm = detectPackageManager();
    log(`\n${c.dim}Ejecutando ${pm} run db:migrate…${c.reset}`);
    const ok = runMigration(projectRoot, pm);
    log(
      ok
        ? `${c.green}✔ Migración aplicada.${c.reset}`
        : `${c.yellow}⚠ La migración falló — revisa ${filename} y ejecútala manualmente.${c.reset}`,
    );
  }

  log(`\n${c.bold}${c.green}Listo!${c.reset} "${table}" tiene ${fields.length} campo(s) nuevo(s).`);
  if (!runNow)
    log(`  Ejecuta ${c.cyan}db:migrate${c.reset} para aplicar los cambios a la base de datos.`);
  log(`  Reinicia ${c.cyan}dev${c.reset} si estaba corriendo.\n`);
}

main().catch((err) => {
  console.error(`${c.red}✖ ${err?.message ?? err}${c.reset}`);
  process.exit(1);
});
